package com.afet.koordinasyon.domain.enums;

public enum EmailNotificationType {
    // Hesap / Güvenlik
    USER_REGISTERED,
    EMAIL_VERIFICATION,
    PASSWORD_RESET,
    PASSWORD_CHANGED,

    // Görev / Gönüllü süreci
    VOLUNTEER_JOIN_RECEIVED,
    VOLUNTEER_JOIN_COORDINATOR_NOTICE,
    VOLUNTEER_JOIN_APPROVED,
    VOLUNTEER_JOIN_REJECTED,
    TASK_ASSIGNED,
    TASK_UPDATED,
    TASK_CANCELLED,
    TASK_COMPLETED,

    // Hasar tespit süreci
    DAMAGE_REPORT_CREATED,
    DAMAGE_REPORT_COORDINATOR_NOTICE,
    DAMAGE_REPORT_STATUS_CHANGED,
    DAMAGE_REPORT_APPROVED,
    DAMAGE_REPORT_REJECTED,
    DAMAGE_REPORT_FIELD_TEAM_ASSIGNED,
    DAMAGE_REPORT_COMPLETED,

    // Ekip / Operasyon
    TEAM_JOIN_RECEIVED,
    TEAM_JOIN_APPROVED,
    TEAM_LEADER_ASSIGNED,
    TEAM_MEMBER_REMOVED,
    TEAM_NEW_TASK_ANNOUNCEMENT,

    // Deprem / Afet
    EARTHQUAKE_ALERT,
    ASSEMBLY_AREA_INFO,
    ASSEMBLY_AREA_UPDATED,

    // Yardım / Kaynak talebi
    AID_REQUEST_CREATED,
    AID_REQUEST_COORDINATOR_NOTICE,
    AID_REQUEST_MATCHED,
    AID_REQUEST_COMPLETED,
    AID_REQUEST_STATUS_CHANGED,

    // Belge onay / red
    DOCUMENT_APPROVED,
    DOCUMENT_REJECTED,

    // Koordinasyon merkezi konumu
    COORDINATION_CENTER_SET,

    // Koordinatör ataması
    COORDINATOR_ASSIGNED,

    // Görev daveti
    TASK_INVITATION,
    TASK_INVITATION_ACCEPTED,

    // Admin / Sistem
    SYSTEM_CRITICAL_ERROR,
    AFAD_POLLING_ERROR
}
