package com.afet.koordinasyon.dto.request;

import com.afet.koordinasyon.domain.enums.DamageLevel;
import com.afet.koordinasyon.domain.enums.LocationSource;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

import java.util.UUID;

@Data
public class CreateDamageAssessmentRequest {

    @NotNull
    private UUID neighborhoodId;

    /**
     * Opsiyonel — haritada gerçek bir bina seçildiyse. Doluysa, bu isteğin address/latitude/
     * longitude/streetName/buildingNo alanları YOK SAYILIR: kanonik değerler Building kaydından
     * sunucu tarafında türetilir (bkz. DamageAssessmentService.create()) — istemciden gelen
     * konum bilgisine asla güvenilmez.
     */
    private UUID buildingId;

    private String streetName;
    private String buildingNo;

    @NotBlank
    private String address;

    @NotNull(message = "Bina konumu zorunludur")
    private Double latitude;

    @NotNull(message = "Bina konumu zorunludur")
    private Double longitude;

    private LocationSource locationSource;
    private Boolean locationVerified;

    private String buildingType;
    private Integer floorCount;
    private String occupancyType;
    private DamageLevel damageLevel;
    private Boolean collapseRisk;
    private Boolean emergencyEvacuationNeeded;
    private Boolean casualtiesSuspected;
    private Boolean blockedRoad;
    private Boolean gasLeakRisk;
    private String note;

    /** Optional UUID generated by the client for offline-queue idempotency. */
    private String clientGeneratedId;
}
