package com.afet.koordinasyon.dto.request;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

import java.util.UUID;

@Data
public class SendStatusMessageRequest {
    private UUID simulationId;

    @NotBlank
    private String templateKey;

    /** Optional UUID generated by the client for offline-queue idempotency. */
    private String clientGeneratedId;
}
