package com.afet.koordinasyon.dto.request;

import jakarta.validation.constraints.NotBlank;
import lombok.Data;

import java.util.UUID;

@Data
public class SendStatusMessageRequest {
    private UUID simulationId;

    @NotBlank
    private String templateKey;

    /** Optional UUID generated by the client for offline-queue idempotency. */
    private String clientGeneratedId;

    /** Opsiyonel konum — yalnızca acil şablonlarda kullanılır (NEED_HELP, TRAPPED_UNDER_RUBBLE). */
    private Double latitude;

    /** Opsiyonel konum boylamı. */
    private Double longitude;

    /** Opsiyonel konum doğruluğu (metre). */
    private Double locationAccuracy;
}
